version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # Eventualy we will want to mount to some external storage like Azure Key Vault
      - ./ssl:/ssl/
      - webserver-log:/etc/nginx/error_log.log
    ports:
      - 80:80
      - 443:443
  
  web:
    build:
      context: .
    volumes:
      - .:/app
      # Prevent these directories from mounting so they're not shared between host OS and Docker
      - /app/node_modules/
      - /app/tmp/
      # Mount these upload directories so they persist between runs
      - web-traces:/home/osm/traces
      - web-images:/home/osm/images
    expose:
      - "3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
      - mailhog

  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "54321:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: openstreetmap
    volumes:
      # Mount the Postgres data directory so it persists between runs
      - db-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  web-traces:
  web-images:
  webserver-log:
  db-data:
